Fruits:
  - name: گوچه سبز
    image: images/Fruits/goje-sabz.jpg
  - name: توت فرنگی
    image: images/Fruits/tot-farangi.jpg
  - name: گیلاس
    image: images/Fruits/gilas.jpg
  - name: آلبالو  
    image: images/Fruits/albaloo.jpg
  - name: زردآلو
    image: images/Fruits/zardaloo.jpg
  - name: هلو
    image: images/Fruits/holoo.jpg
  - name: شلیل
    image: images/Fruits/shalil.jpg
  - name: آلو
    image: images/Fruits/aloo.jpg
  - name: گلابی
    image: images/Fruits/golabi.jpg
  - name: سیب
    image: images/Fruits/sib.jpg
  - name: انار
    image: images/Fruits/anar.jpg
  - name: خرمالو
    image: images/Fruits/khormaloo.jpg
  - name: هندوانه
    image: images/Fruits/hendovane.jpg
  - name: طالبی
    image: images/Fruits/talabi.jpg
  - name: خربزه
    image: images/Fruits/kharboze.jpg
  - name: پرتقال
    image: images/Fruits/porteghal.jpg
  - name: نارنگی
    image: images/Fruits/narenji.jpg
  - name: لیمو
    image: images/Fruits/limoo.jpg
  - name: موز
    image: images/Fruits/moz.jpg
  - name: انگور
    image: images/Fruits/angor.jpg
  - name: انجیر
    image: images/Fruits/anjir.jpg
  - name: آناناس
    image: images/Fruits/ananas.jpg
  - name: کیوی
    image: images/Fruits/kiwi.jpg


Football:
  - name: رئال مادرید
    image: images/Football/real-madrid.jpg
  - name: بارسلونا
    image: images/Football/barcelona.jpg
  - name: اتلتیکو مادرید
    image: images/Football/atletico-madrid.jpg
  - name: منچسترسیتی
    image: images/Football/manchester-city.jpg
  - name: منچستریونایتد
    image: images/Football/manchester-united.jpg
  - name: لیورپول
    image: images/Football/liverpool.jpg
  - name: آرسنال
    image: images/Football/arsenal.jpg
  - name: چلسی
    image: images/Football/chelsea.jpg
  - name: بایرن مونیخ
    image: images/Football/bayern-munich.jpg
  - name: دورتموند
    image: images/Football/dortmund.jpg
  - name: پاریسن ژرمن
    image: images/Football/paris-saint-germain.jpg
  - name: یوونتوس
    image: images/Football/juventus.jpg
  - name: اینتر میلان
    image: images/Football/inter-milan.jpg
  - name: میلان
    image: images/Football/milan.jpg



Animations:
- name: شرکت هیولاها
  image: images/Animations/monster.jpg
- name: در جستجوی نمو
  image: images/Animations/finding-nemo.jpg
- name: شگفت‌انگیزان
  image: images/Animations/incredibles.jpg
- name: ماشین‌ها
  image: images/Animations/cars.jpg
- name: راتاتویی
  image: images/Animations/ratatouille.jpg
- name: وال-ئی
  image: images/Animations/walle.jpg
- name: بالا
  image: images/Animations/up.jpg
- name: داستان اسباب‌بازی‌ها ۱
  image: images/Animations/toy-story-1.jpg
- name: داستان اسباب‌بازی‌ها ۲
  image: images/Animations/toy-story-2.jpeg
- name: داستان اسباب‌بازی‌ها ۳
  image: images/Animations/toy-story-3.jpg
- name: داستان اسباب‌بازی‌ها ۴
  image: images/Animations/toy-story-4.jpeg






